# Usage: gen_anfc_tests_support_files (path to OpenPrintTag repo directory)
# Generates various support files for the OPTReader tests:
# - Header with field types (taken from the OPT repo yamls)
# - Sample NDEF tags contents (for byte-to-byte comparisons in the tests, generated using the OPT repo util scripts)

import sys
import os
import yaml
import subprocess
import tempfile
import uuid

source_dir = os.path.dirname(os.path.abspath(__file__))
materials_dir = sys.argv[1]

f = open("sample_data.cpp.in", "w")
f.write("// AUTO-GENERATED BY anfc_tests_autogen.py\n\n")
f.write("namespace tag_data {\n\n")


def write_bytes(variable, data):
    f.write(f"const ByteString {variable} {{\n")
    f.write(", ".join([f"std::byte({str(int(b))})" for b in data]))
    f.write("\n};\n\n")


def write_sample_data(namespace, data, info=True):
    f.write(f"namespace {namespace} {{\n")

    if info:
        nfc_info = subprocess.run(
            [
                sys.executable,
                os.path.join(materials_dir, "utils", "rec_info.py"),
                "--show-all",
                "--show-raw",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            input=data,
        ).stdout.decode("UTF-8")

        nfc_info_yaml = yaml.safe_load(nfc_info)

        def write_region_info(region):
            if nfc_info is None:
                return

            i = nfc_info_yaml["regions"].get(region, None)
            if i is None:
                return

            f.write(
                f"constexpr PayloadSpan {region}_span {{ .offset = {i['absolute_offset']}, .size = {i['size']} }};\n"
            )
            f.write(
                f"constexpr PayloadPos {region}_payload_offset = {i['payload_offset']};\n"
            )

        write_region_info("meta")
        write_region_info("main")
        write_region_info("aux")

        f.write("/*\n")
        f.write("\n".join([f"* {val}" for val in nfc_info.split("\n")]))
        f.write("\n*/\n")

    write_bytes("data", data)
    f.write("}\n")


def nfc_initialize(params=[]):
    return subprocess.run(
        [
            sys.executable,
            os.path.join(materials_dir, "utils", "nfc_initialize.py")
        ] + params,
        stdout=subprocess.PIPE,
    ).stdout


def nfc_update(input_data, update_data: dict = {}, remove_fields: dict = {}):
    with tempfile.NamedTemporaryFile(delete_on_close=False) as f:
        f.write(
            yaml.safe_dump({
                "data": update_data,
                "remove": remove_fields
            },
                           sort_keys=False).encode("UTF-8"))
        f.close()

        r = subprocess.run(
            [
                sys.executable,
                os.path.join(materials_dir, "utils", "rec_update.py"),
                f.name,
                "--no-canonical",
            ],
            input=input_data,
            stdout=subprocess.PIPE,
        )

        assert r.returncode == 0
        return r.stdout


standard_empty_tag = nfc_initialize(["-s=304", "-b=4"])
standard_empty_tag_with_aux = nfc_initialize(["-s=304", "-b=4", "-a=32"])
empty_tag_with_big_meta_section = nfc_initialize(
    ["-s=256", "-m=32", "-a=16", "-b=1"])
empty_tag_with_minimal_meta_section = nfc_initialize(["-s=128", "-b=1"])

empty_tag_with_uri = nfc_initialize([
    "-s=304", "-b=4", "-a=32", "--ndef-uri", "https://3dtag.org/c/4ea3c75dc9"
])

material_uuid = uuid.UUID("43dab9d7-326c-4c53-9520-eb36a8fa8315")
write_bytes("material_uuid", material_uuid.bytes)

standard_data = {
    "main": {
        "material_class": "FFF",
        "material_type": "ASA",
        "brand_name": "Prusament",
        "material_name": "PLA Prusa Galaxy Black",
        "nominal_netto_full_weight": 0x1FFFFFFFF,
        "transmission_distance": 0.3,
        "tags": ["glitter", "abrasive"],
        "brand_specific_instance_id": "1",
        "material_uuid": str(material_uuid),
    }
}

standard_sample_tag = nfc_update(standard_empty_tag, standard_data)
write_sample_data("standard_sample_tag", standard_sample_tag)

standard_sample_tag_with_aux = nfc_update(standard_empty_tag_with_aux,
                                          standard_data)
standard_sample_tag_with_aux = nfc_update(standard_sample_tag_with_aux,
                                          {"aux": {
                                              "consumed_weight": 100
                                          }})
write_sample_data("standard_sample_tag_with_aux", standard_sample_tag_with_aux)

write_sample_data("empty_tag_with_big_meta_section",
                  empty_tag_with_big_meta_section)

write_sample_data(
    "tag_with_big_meta_section",
    nfc_update(empty_tag_with_big_meta_section, standard_data),
)

write_sample_data("empty_tag_with_minimal_meta_section",
                  empty_tag_with_minimal_meta_section)

write_sample = nfc_update(standard_sample_tag_with_aux,
                          {"main": {
                              "material_type": "PETG"
                          }})
write_sample_data("write_sample_1", write_sample)

write_sample = nfc_update(write_sample,
                          {"main": {
                              "material_name": "PLA Kura Balaxy Klack"
                          }})
write_sample_data("write_sample_2", write_sample)

write_sample = nfc_update(write_sample,
                          {"main": {
                              "min_nozzle_diameter": 12.5
                          }})
write_sample_data("write_sample_3", write_sample)

write_sample = nfc_update(write_sample, {"aux": {"consumed_weight": 969.12}})
write_sample_data("write_sample_4", write_sample)

write_sample = nfc_update(write_sample, {"aux": {"consumed_weight": 12}})
write_sample_data("write_sample_5", write_sample)

write_sample = nfc_update(write_sample,
                          remove_fields={"main": ["material_type"]})
write_sample_data("write_sample_6", write_sample)

write_sample = nfc_update(write_sample,
                          remove_fields={"aux": ["consumed_weight"]})
write_sample_data("write_sample_7", write_sample)

write_sample = nfc_update(write_sample,
                          {"main": {
                              "brand_specific_instance_id": "12"
                          }})
write_sample_data("write_sample_8", write_sample)

write_sample = nfc_update(
    empty_tag_with_big_meta_section,
    {"meta": {
        "main_region_offset": 400,
        "main_region_size": 100
    }},
)
write_sample_data("corrupt_tag_1", write_sample, info=False)

write_sample = nfc_update(empty_tag_with_big_meta_section,
                          {"meta": {
                              "main_region_size": 400
                          }})
write_sample_data("corrupt_tag_2", write_sample, info=False)

sample_tag_with_uri = nfc_update(empty_tag_with_uri, standard_data)
write_sample_data("sample_tag_with_uri", sample_tag_with_uri)

# Wrong mime with different length than our official one
write_sample_data(
    "wrong_mime",
    nfc_initialize(["-s304", "-c", source_dir + "/config_wrong_mime.yaml"]),
    info=False,
)

# Wrong mime with same length as our official one
write_sample_data(
    "wrong_mime_2",
    nfc_initialize(["-s304", "-c", source_dir + "/config_wrong_mime2.yaml"]),
    info=False,
)

f.write("\n}\n\n")
