import sys
import os
import yaml

source_dir = os.path.dirname(os.path.abspath(__file__))
materials_dir = sys.argv[1]

f = open("fields.hpp.in", "w")
f.write("// AUTO-GENERATED BY opt_fields_gen.py\n\n")


def gen_fields_enum(enum, file, parent, name_field="name", key_field="key"):
    f.write(f"enum class {enum} : {parent} {{\n")

    data = yaml.safe_load(open(os.path.join(materials_dir, "data", file), "r"))
    for row in data:
        if row.get("deprecated", False):
            continue

        f.write(f"  {row[name_field]} = {row[key_field]},\n")

    f.write("};\n\n")


gen_fields_enum("MainField", "main_fields.yaml", "Field")
gen_fields_enum("AuxField", "aux_fields.yaml", "Field")
gen_fields_enum("MaterialClass", "material_class_enum.yaml", "uint8_t")
gen_fields_enum("MaterialType",
                "material_type_enum.yaml",
                "uint16_t",
                name_field="abbreviation")
gen_fields_enum("MaterialTag", "tags_enum.yaml", "uint16_t")
