import sys
import os
import yaml

source_dir = os.path.dirname(os.path.abspath(__file__))
materials_dir = sys.argv[1]
target_dir = sys.argv[2]

os.makedirs(target_dir, exist_ok=True)

f = open(f"{target_dir}/fields.hpp.in", "w")
f.write("// AUTO-GENERATED BY opt_fields_gen.py\n\n")


def item_iterator(file):
    data = yaml.safe_load(open(os.path.join(materials_dir, "data", file), "r"))
    for row in data:
        if row.get("deprecated", False):
            continue

        yield row


def gen_fields_enum(enum, file, parent, name_field="name", key_field="key"):
    f.write(f"enum class {enum} : {parent} {{\n")

    for row in item_iterator(file):
        f.write(f"  {row[name_field]} = {row[key_field]},\n")

    f.write("};\n\n")


def gen_fields_data(field_enum, file):
    gen_fields_enum(field_enum, file, "Field")

    for row in item_iterator(file):
        f.write("template<>\n")
        f.write(f"struct FieldMeta<{field_enum}::{row['name']}> {{\n")

        type = row["type"]
        # Append _ suffix for C++ keywords
        if type == "int" or type == "enum":
            type += "_"

        f.write(
            f"  static constexpr FieldType field_type = FieldType::{type};\n")

        if v := row.get("max_length"):
            f.write(f"  static constexpr PayloadPos max_length = {v};\n")

        if type == "string":
            f.write(
                f"  using Buffer = std::array<char, {row['max_length']}>;\n")

        f.write("};\n\n")


gen_fields_data("MainField", "main_fields.yaml")
gen_fields_data("AuxField", "aux_fields.yaml")

gen_fields_enum("MaterialClass", "material_class_enum.yaml", "uint8_t")
gen_fields_enum("MaterialType",
                "material_type_enum.yaml",
                "uint16_t",
                name_field="abbreviation")

gen_fields_enum("MaterialTag", "tags_enum.yaml", "uint16_t")
