#pragma once

#include <bsod.h>
#include <cstdint>
#include <device/peripherals.hpp>
#include <freertos/binary_semaphore.hpp>
#include <freertos/mutex.hpp>
#include <atomic>
#include <utils/uncopyable.hpp>

namespace i2c {

enum class Result {
    ok = 0,
    error = 1,
    busy_after_retries = 2,
    timeout = 3
};

class Manager : Uncopyable {
public:
    static Manager &get_instance() {
        static Manager instance;
        return instance;
    }

    [[nodiscard]] Result transmit(uint16_t dev_address, uint8_t *data_p, uint16_t size);
    [[nodiscard]] Result receive(uint16_t dev_address, uint8_t *data_p, uint16_t size);

    [[nodiscard]] Result mem_write(uint16_t dev_address, uint16_t mem_address, uint16_t mem_add_size, uint8_t *data_p, uint16_t size);
    [[nodiscard]] Result mem_read(uint16_t dev_address, uint16_t mem_address, uint16_t mem_add_size, uint8_t *data_p, uint16_t size);

    void isr_complete(Result result) {
        isr_result = result;
        semaphore.release_from_isr();
    }

    I2C_HandleTypeDef *handle() {
        return &hi2c;
    }

private:
    static constexpr uint32_t max_retries = 20;
    I2C_HandleTypeDef hi2c;
    freertos::BinarySemaphore semaphore;
    freertos::Mutex mutex;
    std::atomic<Result> isr_result = Result::ok;

    template <typename F>
    [[nodiscard]] Result with_retries(F &&operation);

    [[nodiscard]] Result single_transmit(uint16_t dev_address, uint8_t *data_p, uint16_t size);
    [[nodiscard]] Result single_receive(uint16_t dev_address, uint8_t *data_p, uint16_t size);

    [[nodiscard]] Result single_mem_write(uint16_t dev_address, uint16_t mem_address, uint16_t mem_add_size, uint8_t *data_p, uint16_t size);
    [[nodiscard]] Result single_mem_read(uint16_t dev_address, uint16_t mem_address, uint16_t mem_add_size, uint8_t *data_p, uint16_t size);

    inline uint16_t translate_address(uint16_t address) {
        // STM32 HAL expects 7-bit address shifted left by 1
        if (hi2c.Init.AddressingMode == I2C_ADDRESSINGMODE_7BIT) {
            return (address & 0x7F) << 1;
        } else {
            return address & 0x3FF;
        }
    }

    Manager() {
        hi2c.Instance = I2C1;
        hi2c.Init.OwnAddress1 = 0;
        hi2c.Init.Timing = 0x0070133F; // Generated by stm32 cube IDE for 400kHz I2C speed, 40MHz clock and rise time of 100ns
        hi2c.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
        hi2c.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
        hi2c.Init.OwnAddress2 = 0;
        hi2c.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
        hi2c.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
        if (HAL_I2C_Init(&hi2c) != HAL_OK) {
            bsod_system();
        }
    }
};

} // namespace i2c
