"""Helpers for locating build directories produced by utils/build.py."""

from pathlib import Path
from typing import Optional


def find_latest_build_dir(marker: str = 'firmware',
                          name_prefix: str = '') -> Optional[Path]:
    """Return the build/<name> subdir whose `marker` file was modified most recently.

    Matches the layout produced by utils/build.py and the CMake presets
    generated by `utils/build.py --generate-cmake-presets`. When
    `name_prefix` is given, only subdirs whose name starts with it are
    considered. Returns None when no candidate is found.
    """
    project_root = Path(__file__).resolve().parent.parent
    build_root = project_root / 'build'
    if not build_root.is_dir():
        return None

    best: Optional[Path] = None
    best_mtime = -1.0
    for subdir in build_root.iterdir():
        if not subdir.is_dir():
            continue
        if name_prefix and not subdir.name.startswith(name_prefix):
            continue
        target = subdir / marker
        if not target.is_file():
            continue
        mtime = target.stat().st_mtime
        if mtime > best_mtime:
            best_mtime = mtime
            best = subdir
    return best
