# Usage: gen_anfc_tests_support_files (path to Prusa Materials repo directory)
# Generates various support files for the PrusaNFCReader tests:
# - Header with field types (taken from the Materials repo yamls)
# - Sample NDEF tags contents (for byte-to-byte comparisons in the tests, generated using the Materials repo util scripts)

import sys
import os
import yaml
import subprocess
import tempfile
import ndef

source_dir = os.path.dirname(os.path.abspath(__file__))
materials_dir = sys.argv[1]


def generate_field_enums():
    f = open("field_enums.hpp", "w")
    f.write("#pragma once\n\n")
    f.write("// AUTO-GENERATED BY anfc_tests_autogen.py\n\n")
    f.write("#include <nfc_prusa/prusa_nfc_defines.hpp>\n\n")

    def gen_fields_enum(enum, file, parent):
        f.write(f"enum class {enum} : {parent} {{\n")

        data = yaml.safe_load(
            open(os.path.join(materials_dir, "data", file), "r"))
        for row in data:
            f.write(f"  {row['name']} = {row['key']},\n")

        f.write("};\n\n")

    gen_fields_enum("MainField", "main_fields.yaml", "NFCField")
    gen_fields_enum("AuxField", "aux_fields.yaml", "NFCField")
    gen_fields_enum("MaterialClass", "material_class_enum.yaml", "uint8_t")
    gen_fields_enum("MaterialType", "material_type_enum.yaml", "uint16_t")
    gen_fields_enum("MaterialTag", "tags_enum.yaml", "uint16_t")


generate_field_enums()

f = open("sample_data.cpp.in", "w")
f.write("// AUTO-GENERATED BY anfc_tests_autogen.py\n\n")
f.write("namespace tag_data {\n\n")


def write_sample_data(variable, data):
    nfc_info = subprocess.run(
        [
            sys.executable,
            os.path.join(materials_dir, "utils", "rec_info.py"),
            "--show-all",
            "--show-raw",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        input=data,
    ).stdout.decode("UTF-8")

    f.write("/*\n")
    f.write("\n".join([f"* {val}" for val in nfc_info.split("\n")]))
    f.write("\n*/\n")

    f.write(f"const ByteString {variable} {{\n")
    f.write(", ".join([str(int(b)) for b in data]))
    f.write("\n};\n\n")


def nfc_initialize(params=[]):
    return subprocess.run(
        [
            sys.executable,
            os.path.join(materials_dir, "utils", "nfc_initialize.py")
        ] + params,
        stdout=subprocess.PIPE,
    ).stdout


def nfc_update(input_data, update_data: dict = {}, remove_fields: dict = {}):
    with tempfile.NamedTemporaryFile(delete_on_close=False) as f:
        f.write(
            yaml.safe_dump({
                "data": update_data,
                "remove": remove_fields
            },
                           sort_keys=False).encode("UTF-8"))
        f.close()

        return subprocess.run(
            [
                sys.executable,
                os.path.join(materials_dir, "utils", "rec_update.py"), f.name,
                "--no-canonical"
            ],
            input=input_data,
            stdout=subprocess.PIPE,
        ).stdout


standard_empty_tag = nfc_initialize(["-s=300", "-b=4"])
standard_empty_tag_with_aux = nfc_initialize(["-s=300", "-b=4", "-a=32"])
empty_tag_with_big_meta_section = nfc_initialize(
    ["-s=256", "-m=32", "-a=16", "-b=1"])
empty_tag_with_minimal_meta_section = nfc_initialize(["-s=128", "-b=1"])

standard_data = {
    "main": {
        "material_class": "FFF",
        "material_type": "ASA",
        "brand": "Prusament",
        "material_name": "PLA Prusa Galaxy Black",
        "is_signed": False,
        "netto_full_weight": 0x1FFFFFFFF,
        "transmission_distance": 0.3,
        "tags": ["glitter", "abrasive"],
    }
}

standard_sample_tag = nfc_update(standard_empty_tag, standard_data)
write_sample_data("standard_sample_tag", standard_sample_tag)

standard_sample_tag_with_aux = nfc_update(standard_empty_tag_with_aux,
                                          standard_data)
standard_sample_tag_with_aux = nfc_update(standard_sample_tag_with_aux,
                                          {"aux": {
                                              "consumed_material": 100
                                          }})
write_sample_data("standard_sample_tag_with_aux", standard_sample_tag_with_aux)

write_sample_data("empty_tag_with_big_meta_section",
                  empty_tag_with_big_meta_section)
write_sample_data("empty_tag_with_minimal_meta_section",
                  empty_tag_with_minimal_meta_section)

write_sample = nfc_update(standard_sample_tag_with_aux,
                          {"main": {
                              "material_type": "PETG"
                          }})
write_sample_data("write_sample_1", write_sample)

write_sample = nfc_update(write_sample,
                          {"main": {
                              "material_name": "PLA Kura Balaxy Klack"
                          }})
write_sample_data("write_sample_2", write_sample)

write_sample = nfc_update(write_sample,
                          {"main": {
                              "min_nozzle_diameter": 12.5
                          }})
write_sample_data("write_sample_3", write_sample)

write_sample = nfc_update(write_sample, {"aux": {"consumed_material": 969.12}})
write_sample_data("write_sample_4", write_sample)

write_sample = nfc_update(write_sample, {"aux": {"consumed_material": 12}})
write_sample_data("write_sample_5", write_sample)

write_sample = nfc_update(write_sample,
                          remove_fields={"main": ["material_type"]})
write_sample_data("write_sample_6", write_sample)

write_sample = nfc_update(write_sample,
                          remove_fields={"aux": ["consumed_material"]})
write_sample_data("write_sample_7", write_sample)

write_sample = nfc_update(
    empty_tag_with_big_meta_section,
    {"meta": {
        "main_region_offset": 400,
        "main_region_size": 100
    }},
)
write_sample_data("corrupt_tag_1", write_sample)

write_sample = nfc_update(empty_tag_with_big_meta_section,
                          {"meta": {
                              "main_region_size": 400
                          }})
write_sample_data("corrupt_tag_2", write_sample)

# Wrong mime with different length than our official one
write_sample_data(
    "wrong_mime",
    b"".join(
        ndef.message_encoder(
            [ndef.Record("application/vnd.prusa3d.mat.nfcc", "", [])])),
)

# Wrong mime with same length as our official one
write_sample_data(
    "wrong_mime_2",
    b"".join(
        ndef.message_encoder(
            [ndef.Record("application/vnd.prusa3d.mat.nfx", "", [])])),
)

f.write("\n}\n\n")
